### ISSUE TITLE
TensorFlow ValueError: Didn't find op for builtin opcode 'CONV_2D' version '2'

### ISSUE THREAD

**Issue by mec066** [gabemagee/gunshot_detection#11]
Hi, I am trying to run this gunshot detection model on my raspberry pi and I am running into this error when it is reading the tflite model ... Any ideas would be appreciated!!
Error:
Traceback (most recent call last):
  File "gunshot_sound_detect.py", line 283, in <module>
    interpreter_1 = tf.lite.Interpreter(model_path = "/home/pi/Desktop/1D.tflite")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/interpreter.py", line 55, in __init__
    model_path))
ValueError: Didn't find op for builtin opcode 'CONV_2D' version '2'
Registration failed.

**Comment by amorehead** [comment]
Hi, @mec066. Thanks for reaching out about our work. To start with, which version of TensorFlow/TensorFlow Lite have you installed? And second, which version of the Raspberry Pi (and its OS version) are you using?
