### ISSUE TITLE
Unable to Change Input Audio Source

### ISSUE THREAD

**Issue by Gowtham-Pentela** [gabemagee/gunshot_detection#14]
Hi Alex,

I have tried to replicate the code with minor changes  (change in the audio source) and test it. But when I try to give input from my local device the program is picking up from the device's microphone. The change in the code is 

![image](https://user-images.githubusercontent.com/99071734/219545838-f07ed601-fa42-44e1-bcde-384ef30020cc.png)

I am not aware how to fix this. Could you please help me in fixing this issue?

The code, audio files can be found in the below mentioned GitHub link:

https://github.com/Gowtham-Pentela/Gunshot

Thanks in advance.

Best regards,
Gowtham

**Comment by amorehead** [comment]
I was made aware via email that this issue is no longer relevant. If that is not the case, please let me know, and I would be happy to re-open this issue.
