### ISSUE TITLE
Where can I find all_labels.npy?

### ISSUE THREAD

**Issue by jacky0327** [gabemagee/gunshot_detection#5]
## Loading in Augmented Labels
labels = np.load("~/Datasets/all_labels.npy")

Where can I find all_labels.npy?

**Comment by amorehead** [comment]
Jacky,

Thank you for pointing this discrepancy out. The correct filename should be 'augmented_labels.npy' (https://dataverse.harvard.edu/file.xhtml?fileId=4152235&version=1.0) rather than 'all_labels.npy'. I will revise this oversight and push it up to master shortly.

**Comment by amorehead** [comment]
The labels filename has been updated in both the [standalone Python script](https://github.com/gabemagee/gunshot_detection/commit/3873603a4e3795a1e74108fb0292d979519ec3ec#diff-2c631976b77d697253434100c43498529124f289fbd3ef9cae9817f1d40d9228) and the [Jupyter notebook](https://github.com/gabemagee/gunshot_detection/commit/520fc5bb89110350edf1f4d8275defa5d962b8dd#diff-e8916d3e24737353351049b6b60c3996492d5c057762dab9c2d2dd55621a96dc) accompanying it. If you have any other questions, please let us know.

**Comment by jacky0327** [comment]
@amorehead Thank you for the update. I have other questions, and I will ask you in another issue, thanks.
