### ISSUE TITLE
About real-time gunshots detection using mic on localhost

### ISSUE THREAD

**Issue by jackypeng95** [gabemagee/gunshot_detection#6]
When I tested your code today, I encountered two problems.
First of all, I want to tell you about my recent research on real-time gunshot detection.
The initial goal is to use a USB microphone, and use the deep learning model algorithm on the localhost to detect gunshots in real-time.

The first error is as follows:
[Errno 2] could not open port /dev/ttyUSB0

The second error is as follows:
IOError: [Errno Invalid output device (no default output device)] -9996
For example, the question in this article:
https://stackoverflow.com/questions/38470321/ioerror-errno-invalid-output-device-no-default-output-device-9996

I still haven't solved the above two problems, thank you for your reply.

If I only use a USB microphone and use the local program as a test to output the results, can I comment out the Thread for sending SMS and the Thread for Callback?

**Comment by amorehead** [comment]
Jacky,

The first question I have about your research project is, what platform you are targeting for the inference pipeline? The reason I ask is because PyAudio's stream configuration is often tightly coupled to the hardware configuration of the device being used.

**Comment by jacky0327** [comment]
@amorehead 
Sorry, I forgot to tell you about my environment and platform.
The following is my test platform:
OS: Ubuntu 20.04 LTS
Python Env: 
Anaconda (Python 3.7)
The python environment uses your requirements.txt directly, the difference is that I use the tf gpu version.
tensorflow-gpu: 1.14.0
i7-9700K and Nvidia 1080Ti

Is there anything else I need to add?

Thanks.

**Comment by amorehead** [comment]
Jacky,

Thank you for sharing this information.

To go back to your first question, the first error you mentioned is related to the script not being able to identify a USB GSM modem for sending SMS messages (e.g. alerts). To address this, you can start by commenting out lines 375-377. The error is coming from send_sms_alert() when it tries to connect to a modem via the port '/dev/ttyUSB0'. However, in doing so, be aware that on lines 485 and 488 sound samples and their respective metadata are still being added to the sms_alert_queue which potentially could overflow if the script detects enough positive samples (hopefully not)! To remedy this, you can also comment out lines 485 and 488, and even line 491 if you don't want a new WAV file being generated for every positive sample.

The second error you reported is specific to your USB microphone hardware configuration on Ubuntu. You might have to do some research (i.e. trial and error and hardware-specific searches) to determine the correct 'input_device_index' parameter for PyAudio to recognize the microphone correctly (i.e. start by adjusting the AUDIO_DEVICE_INDEX value at the top of the file). This input index value is seemingly different for almost every combination of USB microphones and OS's.

Finally, to answer your question about threading, PyAudio still needs to use the callback and audio_analysis threads, so if possible you'll want to leave those in the code.

I hope this response helps answer some of your questions, although please do not hesitate to ask more if you have some!

**Comment by jackypeng95** [comment]
@amorehead 

Thank you very much for your suggestion!
I used the following code to detect my microphone and tested it repeatedly according to your suggestions.
Finally I found it yaaaaaa!!!

-------------------------------------------------------------------------------------------------------------------------

import pyaudio
p = pyaudio.PyAudio()
info = p.get_host_api_info_by_index(0)
numdevices = info.get('deviceCount')
for i in range(0, numdevices):
        if (p.get_device_info_by_host_api_device_index(0, i).get('maxInputChannels')) > 0:
            print("Input Device id ", i, " - ", p.get_device_info_by_host_api_device_index(0, i).get('name'))

-------------------------------------------------------------------------------------------------------------------------

Output:
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Input Device id  0  -  HDA Intel PCH: ALC1220 Analog (hw:0,0)
Input Device id  1  -  HDA Intel PCH: ALC1220 Alt Analog (hw:0,2)
Input Device id  21  -  sysdefault
Input Device id  30  -  samplerate
Input Device id  31  -  speexrate
Input Device id  32  -  pulse
Input Device id  33  -  upmix
Input Device id  34  -  vdownmix
Input Device id  36  -  default

-------------------------------------------------------------------------------------------------------------------------

Do you have any ideas about the following errors? I have tried many methods, but none of them can be solved, but it still does not affect the operation of the program:
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card

-------------------------------------------------------------------------------------------------------------------------

        model_1_activated = probabilities_1[0][1] >= MODEL_CONFIDENCE_THRESHOLD
        model_2_activated = probabilities_2[0][1] >= MODEL_CONFIDENCE_THRESHOLD
        model_3_activated = probabilities_3[0][1] >= MODEL_CONFIDENCE_THRESHOLD

        if model_1_activated and model_2_activated or model_2_activated and model_3_activated or model_1_activated and model_3_activated:

            print("Gunshot Detected")
            print('%f' % probabilities_1[0][1])
            print('%f' % probabilities_2[0][1])
            print('%f' % probabilities_3[0][1])

-------------------------------------------------------------------------------------------------------------------------

I use my phone to play gunshots and results:
Gunshot Detected
0.993904
0.995511
0.999637

-------------------------------------------------------------------------------------------------------------------------

Can you provide your method of how to train the model? If I expand the data in the future, I hope I can retrain and fine-tune the parameters.

Thanks!

**Comment by jackypeng95** [comment]
These source codes you wrote are really shocking to me. These are amazing gunshot detection!

Report with you the problems I encountered during the test. I have prepared 3 questions to ask you.
The first question:
When I used this code to detect gunshots, I encountered an output that I couldn't understand.

------------------------------------------------------------------------------------------

    model_1_activated = probabilities_1[0][1] >= MODEL_CONFIDENCE_THRESHOLD
    model_2_activated = probabilities_2[0][1] >= MODEL_CONFIDENCE_THRESHOLD
    model_3_activated = probabilities_3[0][1] >= MODEL_CONFIDENCE_THRESHOLD

    if model_1_activated and model_2_activated or model_2_activated and model_3_activated or model_1_activated and model_3_activated:

        print("Gunshot Detected")
        print('%f' % probabilities_1[0][1])
        print('%f' % probabilities_2[0][1])
        print('%f' % probabilities_3[0][1])

------------------------------------------------------------------------------------------

Output:
Gunshot Detected
0.001536
0.025863
0.000354

------------------------------------------------------------------------------------------

I use my iphone to broadcast gunshots and occasionally encounter this situation.
Why is the prediction confidence level below the threshold still outputting "Gunshot detected"?

The second question:
I am a newbie to python pyaudio, I would like to ask you how to input one or more local computer's .wav audio files, and detecting from models threads, and output the results?
I need to put a lot of .wav audio files in a folder for batch detecting.

The third question:
How can I use your framework to train a custom model? Includes 3 models (.tflite 3 and .h5 3)

Thank you very much! I look forward to your reply!

**Comment by amorehead** [comment]
Jacky,

I'm glad to hear that you were able to get the pipeline up and running. It looks like your results indicate that it is working to at least some extent! Regarding your question about the following errors, I cannot say much as it they must be related to how PyAudio interfaces with your computer's sound hardware:

ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card

Concerning your question about how to train the three models (the 1D CNN and the two 2D CNNs (1st: 128x64 and 2nd: 128x128)), for that code you will have to look at the project's develop branch. There, you will see several directories, including mine, for how we trained the different models. Those Python scripts should get you started.

**Comment by amorehead** [comment]
Jacky,

In response to your first question, what is your MODEL_CONFIDENCE_THRESHOLD set to?

For your second question, off the top of my head, I cannot say in specific detail. You would have to modify lines [415 and on](https://github.com/gabemagee/gunshot_detection/blob/master/raspberry_pi/gunshot_detection.py) to no longer use PyAudio's callback mode as that mode most often used for streaming audio sources. On line 420 of the same file, you would need to rework how the data is being passed into the three models (i.e. instead of having it use audio_analysis_queue.get() to fetch the latest two-second audio clip curated by PyAudio's callback thread). You could possibly make the infinite while loop on line 415 a for loop over each of the WAV files in the directory you talked about and then process and analyze each of such files using the proceeding logic.

And for your third question, to be more specific than my last response, I would recommend you look at the [1D CNN](https://github.com/gabemagee/gunshot_detection/tree/develop/python/Alex/1D%20CNN) and [2D CNN](https://github.com/gabemagee/gunshot_detection/tree/develop/python/Alex/2D%20CNN) directories to get started training your own models.

**Comment by jackypeng95** [comment]
@amorehead 

The threshold I set is 0.5.
MODEL_CONFIDENCE_THRESHOLD = 0.5
I want to know the confidence of .wav after each model.
I print('%f'% probabilities_1[0][1]), it's correct?
I still don't understand why gunshots are still detected when it is lower than 0.5.
About my computer's sound hardware, I know that the warning will not affect the results. 
Sorry, thank you for your reminder. I accidentally ignored the branch. I will start to check and research. Thank you for your reply.
Thank you for replying to my second and third question. I roughly know how to do third question, and I will share it with you when I am finished.
Regarding the second question, I need time to study it, thank you for your advice and teach!!!

**Comment by amorehead** [comment]
Jacky,

Regarding your question about the confidence threshold, it might be caused by an indentation discrepancy in Python. That is, assuming the logic is correct (which I believe it is), it's possible your indentation is off in text editor you are using. If so, Python's interpreter could potentially skip over the if check and continue to execute the print statements even if the if check evaluated to False. I hope this makes sense.
