### ISSUE TITLE
About Keras .h5

### ISSUE THREAD

**Issue by jackypeng95** [gabemagee/gunshot_detection#7]
@amorehead 

Can this gunshot_detection.py be able to load keras .h5 weights?

When I use this,

interpreter_1 = tf.lite.Interpreter(model_path = "/home/jacky/gunshot/gunshot_detection/Trained_Models/Trained_Keras_Models/1D.h5")
interpreter_1.allocate_tensors()

input_details_1 = interpreter_1.get_input_details()
output_details_1 = interpreter_1.get_output_details()
input_shape_1 = input_details_1[0]['shape']

I got this error,

Traceback (most recent call last):
  File "gunshot_detection.py", line 293, in <module>
    interpreter_1 = tf.lite.Interpreter(model_path = "/home/jacky/gunshot/gunshot_detection/Trained_Models/Trained_Keras_Models/1D.h5")
  File "/home/jacky/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 77, in __init__
    model_path))
ValueError: Model provided has model identifier '
�
', should be 'TFL3'

**Comment by amorehead** [comment]
Jacky,

I would reference this previous commit in the project's develop branch to see how we used to use .h5 models in the pipeline: https://github.com/gabemagee/gunshot_detection/commit/f05790f0928d7cbf5794dc7c6a44a3a5ba9ed376. Let me know if this helps.

**Comment by jackypeng95** [comment]
@amorehead 
Thank you for your provided reference, tflite's loading is very low, but the accuracy is comparable to keras .h5?

**Comment by amorehead** [comment]
Jacky,

Yes, that is generally the case. .tflite models typically consume less storage space to achieve inference performance comparable to their .h5 model counterparts, but they also often take longer to load.

**Comment by jackypeng95** [comment]
@amorehead 
Your paper compares the experiments between the two models. In fact, there is almost no difference, and it can even be said to achieve exactly the same accuracy. Could it be because deep learning related to spectrogram (voicegram) usually does not require too large models and deep neural network layers?

My major is deep learning related to computer vision.

**Comment by amorehead** [comment]
Jacky,

I believe this is one possible explanation for why the performance between the two kinds of models is very similar. It is also possible that the quantization being applied to the .tflite models ultimately does not negatively impact the spectrograms' latent representations when being passed through the models.
