### ISSUE TITLE
About the gunshot spectrogram

### ISSUE THREAD

**Issue by jayer95** [gabemagee/gunshot_detection#8]
I would like to ask you about the relevant background of spectrogram.

In the paper, it is mentioned that the spectrogram is used as the main input for CNN training. 
What kind ofspectrogram does the librosa package in python convert every 2 seconds of recording?

I refer to the official website of the librosa package. There are many parameters for librosa to convert the sound into a waveform graph and a waveform graph convert into the spectrogram. (e.g. mel spectrogram)
ref. https://librosa.org/doc/latest/index.html

When a gunshot is detected, I want to use librosa's parameters to print out the detected 2 second gunshot instantly.

What should I do? I want to use matplotlib.pyplot to print out the waveform graph and the spectrogram converted from the waveform graph (the spectrogram of your paper), whenever I detected gunshots. (import matplotlib.pyplot as plt)

I want to use this to observe the difference in the distance of the spectrogram of gunshots real-time and how it differs from the gunshots recorded by different microphones.

Can I change the program that records every 2 seconds to an overlap of 1 second between the first 2 seconds and the last 2 seconds, so that the detection will not miss more opportunities to detect gunshots?

**Comment by amorehead** [comment]
Jacky,

1. Librosa computes a "Mel Spectrogram" (https://towardsdatascience.com/getting-to-know-the-mel-spectrogram-31bca3e2d9d0) of each two-second slice of audio data. This is a commonly-used format in signal processing. The parameters we use to convert a NumPy array containing two seconds worth of audio data can be seen in our pipeline's main script (https://github.com/gabemagee/gunshot_detection/blob/master/raspberry_pi/gunshot_detection.ipynb) in the section titled "Converting 1D Sound Arrays into Spectrograms".

2. If you want to plot the detected two seconds of audio data, in the section titled "Audio Analysis Thread" in our main script (https://github.com/gabemagee/gunshot_detection/blob/master/raspberry_pi/gunshot_detection.ipynb), you'll want to replace the lines

        # Passes an audio sample of an appropriate format into the model for inference
        processed_data_1 = modified_microphone_data
        processed_data_1 = processed_data_1.reshape(input_shape_1)

        HOP_LENGTH = 345 * 2
        processed_data_2 = convert_audio_to_spectrogram(data = modified_microphone_data)
        processed_data_2 = processed_data_2.reshape(input_shape_2)
            
        HOP_LENGTH = 345
        processed_data_3 = convert_audio_to_spectrogram(data = modified_microphone_data)
        processed_data_3 = processed_data_3.reshape(input_shape_3)

with something like

        # Passes an audio sample of an appropriate format into the model for inference
        processed_data_1_orig = modified_microphone_data
        processed_data_1 = processed_data_1_orig.reshape(input_shape_1)

        HOP_LENGTH = 345 * 2
        processed_data_2_orig = convert_audio_to_spectrogram(data = modified_microphone_data)
        processed_data_2 = processed_data_2_orig.reshape(input_shape_2)
            
        HOP_LENGTH = 345
        processed_data_3_orig = convert_audio_to_spectrogram(data = modified_microphone_data)
        processed_data_3 = processed_data_3_orig.reshape(input_shape_3)

so you can pass "processed_data_2_orig" into the Librosa function "librosa.display.specshow(processed_data_2_orig)" (ref: https://librosa.org/doc/latest/auto_examples/plot_display.html). I have not verified if this will work directly (i.e. you may have to experiment with the format or shape of processed_data_2/3_orig to get it to work), but this is where I would start.

3. Concerning the one-second overlap idea, we considered doing something like this originally, but we opted to leave this feature for future work. You are most certainly welcome to create this new feature in the pipeline if you so choose.

**Comment by jayer95** [comment]
Thank you very much for your careful explanation. I already know more about the background of the spectrogram.
The following is the result that I printed immediately.
![S__26599578](https://user-images.githubusercontent.com/35683311/106622816-f55a9000-65ae-11eb-88a7-74b7f02359e0.jpg)
Regarding of the overlapping for 1 second, I will continue to do.
